Add bcrypt_pbkdf to fix ed25519 ssh keys support
This is to fix the following Beaker error:
```
NotImplementedError: unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
Gem::LoadError : "bcrypt_pbkdf is not part of the bundle. Add it to your Gemfile."
```