(BKR-661) Change to use pkgng for FreeBSD
* pkg_* is EOL as of Sept 2014 https://lists.freebsd.org/pipermail/freebsd-ports-announce/2014-February/000077.html
* On most base boxes, the pkg_* pointers are now 404:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

pkg_add -r rsync

Stdout from the command:

Error: Unable to get ftp://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9-stable/Latest/rsync.tbz: File unavailable (e.g., file not found, no access)
```

* Also fixes (BK-438), as we're changing package install result to be the result, as is the same with other pkg helpers.
* Moves FreeBSD checking package code to FreeBSD specific class
* Adds spec for changes