(BKR-583) Fixes incorrect error when MSI missing
`version` variable missing, so get error:

`<NameError: undefined local variable or method 'version'>`

Rather than correct error:

`<RuntimeError: Puppet MSI at /puppet-agent-VERSION-x86.msi does not exist!>`